package cli

import (
	"bytes"
	"embed"
	"fmt"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

//go:embed all:templates
var templatesFS embed.FS

//go:embed all:templates-sample
var sampleFS embed.FS

// dotenvTemplate is the .env template generated by init in every mode. It is
// embedded as a standalone file (not under templates/) so it is not copied by
// writeEmbeddedTree, and so the source file is not matched by the repo's
// .gitignore rule for ".env".
//
//go:embed dotenv.txt
var dotenvTemplate []byte

// writeEnvFile writes the .env template to outputDir/.env. Existing files are
// skipped when force is false (consistent with the other generated files).
func writeEnvFile(cmd *cobra.Command, outputDir string, force bool) error {
	return writeFile(cmd, filepath.Join(outputDir, ".env"), dotenvTemplate, force)
}

type sampleEpisodeSpecData struct {
	WithAssets bool
}

func renderSampleEpisodeSpec(cmd *cobra.Command, dstDir string, withAssets bool, force bool) error {
	tmplContent, err := sampleFS.ReadFile("templates-sample/episode-spec.yaml.tmpl")
	if err != nil {
		return fmt.Errorf("read episode-spec template: %w", err)
	}
	t, err := template.New("episode-spec").Parse(string(tmplContent))
	if err != nil {
		return fmt.Errorf("parse episode-spec template: %w", err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, sampleEpisodeSpecData{WithAssets: withAssets}); err != nil {
		return fmt.Errorf("execute episode-spec template: %w", err)
	}
	return writeFile(cmd, filepath.Join(dstDir, "episode-spec.yaml"), buf.Bytes(), force)
}

func writeSampleFiles(cmd *cobra.Command, outputDir string, withAssets bool) error {
	// assets/assets.yaml はパック展開に委ねるため生成しない（withAssets 時）。
	// episode-spec.yaml はテンプレートから生成する。
	skip := func(rel string) bool {
		if rel == "episode-spec.yaml.tmpl" {
			return true
		}
		return withAssets && strings.HasPrefix(rel, "assets/")
	}
	if err := writeEmbeddedTree(cmd, sampleFS, "templates-sample", outputDir, false, skip); err != nil {
		return err
	}
	return renderSampleEpisodeSpec(cmd, outputDir, withAssets, false)
}

func newInitCmd() *cobra.Command {
	var sample bool
	var sampleWithAssets bool
	var outputDir string

	cmd := &cobra.Command{
		Use:   "init",
		Short: "テンプレート設定ファイルを生成する",
		Long: `vox-radio.yaml（共通設定）・episode-spec.yaml（エピソード仕様）・feed-spec.yaml（フィード生成設定）・slack-spec.yaml（Slack 投稿設定）・assets/assets.yaml（アセット設定）・.env（環境変数テンプレート）を
生成します。Slack 投稿文テンプレート（slack-parent.tmpl・slack-thread.tmpl）は template/ 配下に生成されます。
出力先は --output-dir で指定します（省略時はカレントディレクトリ）。

.env には GEMINI_API_KEY や VOX_RADIO_VOICEVOX_URL などの環境変数の記入欄が含まれます。
プレースホルダを書き換えて利用してください（コマンド実行時に自動で読み込まれます）。

--sample を指定すると、ずんだもん・めたんが MC を務めるお天気番組（気象庁の防災情報XMLを利用）の
「すぐ動くサンプル設定一式」のテンプレートを生成します。--sample を使っても出力先は --output-dir で
決まり、省略時はカレントディレクトリです。旧来の sample/ 配下への出力は次のコマンドで再現できます:

  vox-radio init --sample --output-dir sample

--sample-with-assets を指定すると、サンプル音源パック（sample-assets）を前提に、各コーナーへ
ジングル・SE・BGM を割り当て済みの設定一式を生成します（assets/assets.yaml は生成せず、別途
パックを assets/ に展開して使います）。手順は次のとおりです:

  curl -LO "https://github.com/canpok1/vox-radio/releases/download/v$(vox-radio --version | awk '{print $NF}')/vox-radio-sample-assets.zip"
  unzip vox-radio-sample-assets.zip -d assets
  vox-radio init --sample-with-assets
  vox-radio episodegen --spec episode-spec.yaml

生成後は次のコマンドで番組生成を試せます:

  vox-radio episodegen --spec episode-spec.yaml

既存ファイルは上書きを防ぐため個別にスキップされます。
すべてのファイルがすでに存在する場合は何も生成されません。

生成後は LLM API キーを .env に、番組内容・音声アセットパスを設定ファイルに記入し、
次のコマンドでパイプラインを実行してください:

  vox-radio episodegen --spec episode-spec.yaml`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if sample && sampleWithAssets {
				return fmt.Errorf("--sample と --sample-with-assets は同時に指定できません")
			}
			var err error
			switch {
			case sampleWithAssets:
				err = writeSampleFiles(cmd, outputDir, true)
			case sample:
				err = writeSampleFiles(cmd, outputDir, false)
			default:
				err = writeEmbeddedTree(cmd, templatesFS, "templates", outputDir, false, nil)
			}
			if err != nil {
				return err
			}
			// .env テンプレートは全モードで生成する（既存はスキップ）。
			return writeEnvFile(cmd, outputDir, false)
		},
	}

	cmd.Flags().BoolVar(&sample, "sample", false, "ずんだもん・めたんMCのお天気番組サンプル一式のテンプレートを生成する")
	cmd.Flags().BoolVar(&sampleWithAssets, "sample-with-assets", false, "サンプル音源パック（sample-assets）を前提にアセット割り当て済みのサンプル一式を生成する")
	cmd.Flags().StringVar(&outputDir, "output-dir", ".", "テンプレートの出力先ディレクトリ（省略時はカレントディレクトリ）")

	return cmd
}
