services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached

    command: sleep infinity

  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    ports:
      - "50021:50021"
