name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  packages: write # ghcr.io への Docker イメージ push に必要

jobs:
  release:
    uses: ./.github/workflows/goreleaser.yml
    with:
      goreleaser-args: "release --clean"
    secrets: inherit
